-- Reference fragment. The production table is generated by
-- scripts/build_dynamic_gender_variants_v067.py and compiled into patch_text01.

local GENDERED_MESSAGE = require("gender_message_map")

function ResolveGenderedMessageId(message_id)
  local pair = GENDERED_MESSAGE[message_id]
  if pair == nil and type(message_id) == "number" then
    pair = GENDERED_MESSAGE[tostring(message_id)]
  end
  if pair == nil then return message_id end
  local gender = GetGender()
  if gender == HERO then return pair.hero or message_id end
  if gender == HEROINE then return pair.heroine or message_id end
  return message_id
end

-- Apply the resolver in function_common.lua to each wrapper:
--   Talk.Message(ResolveGenderedMessageId(a_message_id))
--   Talk.Message_Auto(ResolveGenderedMessageId(a_message_id), a_frame)
--   Talk.MessageTalk(ResolveGenderedMessageId(a_message_id), a_visible_speaker)
--   Talk.MessageTalkAuto(ResolveGenderedMessageId(a_message_id), a_frame, a_visible_speaker)
--   Talk.MessageTalkSel(a_sel_num, ResolveGenderedMessageId(a_message_id))
--
-- function_field.lua's four direct Talk.* calls and the seven exceptional calls
-- listed in DYNAMIC_GENDER_AUDIT_v064.md must use the same resolver.
